#!/home/lijo/anaconda2/bin/python -u

import sys, getopt, dbus
from subprocess import Popen, PIPE

def main(argv):
    try:
        opts, args = getopt.getopt(argv,"h:",["help","status","play","pause",
                                              "playpause","next","prev",
                                              "volumeup","volumedown"])
    except getopt.GetoptError:
        show_help()
        sys.exit(2)
    for opt, arg in opts:
        if opt in ("-h", "--help"): show_help()
        elif opt == "--status":     show_current_song()
        elif opt == "--play":       perform_action("Play")
        elif opt == "--pause":      perform_action("Pause")
        elif opt == "--playpause":  perform_action("PlayPause")
        elif opt == "--next":       perform_action("Next")
        elif opt == "--prev":       perform_action("Previous")
        elif opt == "--volumeup":   control_volume("+5%")
        elif opt == "--volumedown": control_volume("-5%")


def show_help():
    print ('\n  music is a command line interface for rhythmbox & spotify on Linux\n\n' \
          '  usage:\n' \
          '    --help, -h\t\tshows help\n' \
          '    --status\t\tshows status (currently played song name and artist)\n' \
          '    --play\t\tplays the song\n' \
          '    --pause\t\tpauses the song\n' \
          '    --playpause\t\tplays or pauses the song (toggles a state)\n' \
          '    --next\t\tplays the next song\n' \
          '    --prev\t\tplays the previous song\n' \
          '    --volumeup\t\tincreases sound volume\n' \
          '    --volumedown\tdecreases sound volume\n') \

def show_current_song():
    try:
        music_bus= bus.get_object("org.mpris.MediaPlayer2.%s" %player, "/org/mpris/MediaPlayer2")
        music_properties = dbus.Interface(music_bus, "org.freedesktop.DBus.Properties")
        metadata = music_properties.Get("org.mpris.MediaPlayer2.Player", "Metadata")

        title = metadata['xesam:title'][:15] + (metadata['xesam:title'][15:] and '...')
        artist = metadata['xesam:artist'][0][:20] + (metadata['xesam:artist'][0][20:] and '...')
        print ("%s - %s" % (artist, title))
    except:
        # we go here when spotify is turned off, not installed or we cannot access dbus
        print ("player is off")

def perform_action(MusicCommand):
    Popen('dbus-send --print-reply --dest=org.mpris.MediaPlayer2.%s ' \
    '/org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player."%s"' % (player, MusicCommand), shell=True, stdout=PIPE)

def control_volume(volumePercent):
    Popen('pactl set-sink-volume 0 "%s"' % volumePercent, shell=True, stdout=PIPE)

if __name__ == "__main__":
    bus = dbus.SessionBus()
    if bus.name_has_owner('org.mpris.MediaPlayer2.rhythmbox'):
        player = "rhythmbox"
    elif bus.name_has_owner('org.mpris.MediaPlayer2.spotify'):
        player = "spotify"
    else:
        print("Player is off")
        sys.exit()
    main(sys.argv[1:])
